djangonautic/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view, name='signup'),
    url(r'^login/$',views.login_view, name='login'),
    url(r'^logout/$',views.logout_user, name='logout'),
]

djangonautic/articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$',views.articles_list, name='list'),
    url(r'^create/',views.article_create, name='article_create'),
    url(r'^(?P<slug>[\w-]+)$',views.article_detail, name='detail'),

]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls')),
    url(r'^about/$',views.aboutpage),
    url(r'^$',views.homepage),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png',blank=True)
    #add author later

    #learn modifications in a table

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

djangonautic/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # login the user
            user = form.save()
            login(request,user)
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            # login the user
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html', {'form': form})

def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

djangonautic/articles/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Article
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/articles_list.html',{'articles':articles})

def article_detail(request,slug):
    articles = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':articles})

def article_title(request,slug):
    articles = Article.objects.get(slug=slug)
    return render(request, 'articles/base_layout.html',{'article':articles})

@login_required(login_url = '/accounts/login/')
def article_create(request):
    return render(request,'articles/article_create.html')

djangonautic/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def aboutpage(request):
    #return HttpResponse("This is Django and i am a champion.")
    return render(request,'about.html')
def homepage(request):
    #return HttpResponse("This is the Homepage and follow me.")
    return render(request,'home.html')

djangonautic/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

<body>
    <h1>Login Form</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
       <input type="submit" value="Login">
    </form>

</body>
</html>

{% endblock %}

djangonautic/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

<body>
    <h1>SignUp Form</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
       <input type="submit" value="SignUp">
    </form>

</body>
</html>

{% endblock %}

djangonautic/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<body>
    <h1>Create an Article</h1>
    {% csrf_token %}
</body>
</html>

{% endblock %}

djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<body>
    <div class="article-detail">
        <div class="article">
            <img src="{{ article.thumb.url }}">
            <h2>{{ article.title }}</h2>
            <p>{{ article.body }}</p>
            <p style="color:#354670;">Created on: {{ article.date }}</p>
        </div>
    </div>
</body>
</html>

{% endblock %}

djangonautic/articles/templates/articles/articles_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>List of articles.</h1>
    <div class="articles">
        {% csrf_token %}
        {% for article in articles %}
            <div class="article">
                <h2 style='color:#000000;'>{{ article.title }}</h2>
                <p>{{ article.snippet }}<a href="{% url 'articles:detail' slug=article.slug %}">[more]</a></p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

djangonautic/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About us</title>
</head>
<body>
    <h1>This is the about us page.</h1>
</body>
</html>

djangonautic/templates/base_layout.html
{% load static from staticfiles %}

<html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ article.slug }}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <a href="{% url 'articles:list' %}"><img src="{% static 'django_logo_1.png' %}"></a>
    <div class="wrapper">
        <nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button class="btn-btn" type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
        {% block content %}

        {% endblock %}
    </div>

</body>
</html>

djangonautic/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>This is the Home Page.</h1>
</body>
</html>